### ISSUE TITLE
Add-on Startup Failed For Forvo

### ISSUE THREAD

**Issue by KotoriDruid** [seth-js/yomichan-de#4]
Following is the debug info:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19044

When loading German Forvo:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\German Forvo\__init__.py", line 149, in <module>
    class ForvoHandler(http.server.SimpleHTTPRequestHandler):
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\German Forvo\__init__.py", line 150, in ForvoHandler
    forvo = Forvo("de")
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\German Forvo\__init__.py", line 28, in __init__
    self._set_session()
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\German Forvo\__init__.py", line 35, in _set_session
    retry_strategy = Retry(
TypeError: __init__() got an unexpected keyword argument 'method_whitelist'

**Comment by seth-js** [comment]
Delete the `German Forvo` folder in your Anki addons directory, and re-download `German.Forvo.zip` from the [Releases](https://github.com/seth-js/yomichan-de/releases/tag/v1.1) page. You can then follow the `Forvo setup` section in the repo's readme. It should be working now.
